<Container>:
    rows: 3

    AnchorLayout:
        TextInput:

    GridLayout:
        cols: 2

        BoxLayout:
            orientation: "vertical"

            Label:
                text: "Paracetamol"

            Label:
                text: "Ipubrofen"

        BoxLayout:
            orientation: "vertical"

            Label:
                text: "0"

            Label:
                text: "0"

    BoxLayout:
        Button:
            text: "Calculate"